name: "CI"

on:
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: ge-tracker/phpcbf-action@v1

#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '7.4'
#          tools: phpcs, phpcbf, phpdoc

#      - name: Detecting PHP Code Standards Violations
#        run: phpcbf -w -v ./
#
#      - name: Running phpdoc
#        run: phpdoc -d
