name: 'PHP CS'
on:
    push:
        branches:
            - master
jobs:
    master:
        name: 'build'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 0
            - name: PHPCS
              run: cd workflow/bin && sudo ./phpcbf ../../admin && git add --all && git commit -m 'hey' && git push
