name: 'PHP Code Sniffer'

on:
  push:
    branches:
      - test_ci

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1


      - name: Validate composer.json and composer.lock
        run: sudo composer validate

      - name: Download php_codesniffer
        run: sudo composer require "squizlabs/php_codesniffer=*" --dev

      - name: Install dependencies
        run: sudo composer install --prefer-dist --no-progress --no-suggest

      - name: Detecting PHP Code Standards Violations
        run: sudo composer run-script phpcs
