name: 'PHP Developper Documentation'
on:
    push:
        branches:
            - master
jobs:
    master:
        name: 'build'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 0
            - name: Developper Documentation
              run: cd workflow/phpdocumentor/phpdocumentor && composer install && cd ../../bin && ./phpdoc -d "..\..\class" -t "..\..\docs"

